# Generated by Django 4.2 on 2023-04-26 17:02

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catigory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catigory', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='RegionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('descriptions', ckeditor.fields.RichTextField()),
                ('short_text', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=25)),
                ('operator', models.CharField(blank=True, max_length=25, null=True)),
                ('montajor', models.CharField(blank=True, max_length=25, null=True)),
                ('catigorys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.catigory')),
                ('regions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.regionmodel')),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.newstype')),
            ],
        ),
    ]
