# Generated by Django 4.2 on 2023-04-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='tg_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
