# Generated by Django 4.2 on 2023-04-27 19:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_newsmodel_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='short_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
