# Generated by Django 4.2 on 2023-05-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_newsmodel_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstype',
            name='title',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
    ]
