# Generated by Django 4.2 on 2023-05-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_newstype_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newstype',
            name='title',
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='news_title',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
    ]
