# Generated by Django 4.2 on 2023-05-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_remove_newstype_title_newsmodel_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='dolzarb',
            field=models.CharField(blank=True, choices=[('+', 'main'), ('-', 'second')], max_length=25, null=True),
        ),
    ]
