# Generated by Django 4.2 on 2023-05-02 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_newsmodel_dolzarb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='author',
        ),
    ]
