# Generated by Django 4.2 on 2023-05-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_remove_newsmodel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='catigorys',
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='catigorys',
            field=models.ManyToManyField(to='newapp.catigory'),
        ),
    ]
